<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Wedding Invitation</title>
  <style>
    body {
      font-family: 'Georgia', serif;
      background-color: #fff8f0;
      margin: 0;
      padding: 0;
      color: #4a2c2a;
    }

    .invitation {
      max-width: 700px;
      margin: auto;
      background: #fff;
      padding: 30px;
      box-shadow: 0 0 20px rgba(0,0,0,0.1);
      border-radius: 12px;
      margin-top: 40px;
      margin-bottom: 40px;
      text-align: center;
    }

    .invitation img {
      width: 100%;
      max-height: 300px;
      object-fit: cover;
      border-radius: 12px;
    }

    h1 {
      font-size: 2em;
      margin: 20px 0 10px;
      color: #b71c1c;
    }

    .names {
      font-size: 1.8em;
      margin: 20px 0;
      color: #c2185b;
    }

    .details {
      font-size: 1.1em;
      line-height: 1.6em;
      margin: 20px 0;
    }

    .location a {
      color: #1565c0;
      text-decoration: none;
    }

    .footer {
      margin-top: 30px;
      font-style: italic;
      color: #5d4037;
    }

    @media (max-width: 600px) {
      .invitation {
        padding: 20px;
      }
    }
  </style>
</head>
<body>

  <div class="invitation">
    <img src="https://t3.ftcdn.net/jpg/06/33/14/24/360_F_633142445_a28s95TfFK6wm8VdCSO8zDEwRfS6bAho.jpg">

    <h1>Wedding Invitation 💐</h1>

    <p class="details">
      Dear Friends and My Family members,
      <br><br>
      With great joy in our hearts, we are delighted to invite you to the wedding of my brother.
    </p>

    <div class="names">
      Somesh 💞 Mamatha
    </div>

    <div class="location">
 <a href="https://maps.app.goo.gl/VfUFMg9Cpz377Xd17" target="_blank" style="
  display: inline-block;
  background-color: #00A693; /* Peacock green */
  color: white;
  padding: 12px 24px;
  border-radius: 6px;
  text-decoration: none;
  font-weight: bold;
  font-size: 1em;
">
  📍 View Location on Google Maps
</a>


</div>


    <p class="details">
      Your presence will mean the world to us as we come together to celebrate love, laughter, and lifelong togetherness.
      Please join us in blessing the couple and making the occasion truly memorable.
    </p>

    <div class="footer">
      We hope to see you there! <br><br>
      Warm regards,<br>
      <strong>Chidananda</strong>
    </div>
  </div>

</body>
</html>

